Update for RevoBoot v1.5.10/v1.5.20

diff --git a/i386/Makefile b/i386/Makefile
--- a/i386/Makefile
+++ b/i386/Makefile
@@ -1,49 +1,36 @@
 #
-#	Makefile for RevoBoot
+# File: RevoBoot/i386/Makefile
 #
-
-CFLAGS	= -O $(MORECPP) -arch i386 -g -static
-CONFIG = hd
-LIBDIR = libsa
-INC = -I. -I$(LIBDIR)
-ifneq "" "$(wildcard /bin/mkdirs)"
-  MKDIRS = /bin/mkdirs
-else
-  MKDIRS = /bin/mkdir -p
-endif
-AS = as
-LD = ld
+# Updates:
+#
+#			- Major cleanup (PikerAlpha, October 2012).
+#			- Output improvements (PikerAlpha, October 2012).
+#
 
 #
 # These paths are only valid in subdirectories of this directory.
 #
 
-OBJROOT=`pwd`/../../obj/i386
-SYMROOT=`pwd`/../../sym/i386
-DSTROOT=`pwd`/../../dst/i386
-SRCROOT=/tmp
+OBJROOT=../i386/obj/i386
+SYMROOT=../i386/sym/i386
 
-VPATH = $(OBJROOT):$(SYMROOT)
+# VPATH = $(OBJROOT):$(SYMROOT)
 
 #
-# The build over here is important.
+# The build order here is important.
 #
 
 SUBDIRS = util libsa libsaio boot2
 
-lion: all
-mountain-lion: all
 
-all:
+$(MAKEGOAL):
 	@for i in ${SUBDIRS}; \
 	do \
-		echo ================= make $@ for $$i =================; \
-		( cd $$i; ${MAKE}					  \
-			"OBJROOT=$(OBJROOT)/$$i"			  \
-		  	"SYMROOT=$(SYMROOT)"				  \
-			"DSTROOT=$(DSTROOT)"				  \
-			"SRCROOT=$(SRCROOT)"				  \
-			"RC_ARCHS=$(RC_ARCHS)"				  \
-			"RC_CFLAGS=$(RC_CFLAGS)" $@ 			  \
-		) || exit $$?; 						  \
+		echo ================= make MODEL=$(PRODUCT_MODEL_TARGET) $@ for: RevoBoot/i386/$$i =================; \
+		( cd $$i; ${MAKE} \
+			"OBJROOT=$(OBJROOT)/$$i" \
+		  	"SYMROOT=$(SYMROOT)" \
+			"RC_ARCHS=$(RC_ARCHS)" \
+			"RC_CFLAGS=$(RC_CFLAGS)" $@ \
+		) || exit $$?; \
 	done
